version: '3.7'

services:
  kong-database:
    image: postgres:14
    container_name: kong-database
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong:
    image: kong:3.2
    container_name: kong
    restart: always
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000" # Kong Proxy
      - "8001:8001" # Kong Admin API
      - "8443:8443" # Kong Proxy SSL
      - "8444:8444" # Kong Admin API SSL

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    depends_on:
      - kong
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337"
